import { getSystemPrompt } from '../config/prompts';

// ⚠️ MODEL CONFIGURATION - Update this if the model gets deprecated!
// Current working model: gemini-2.5-flash (stable version, as of Jan 2026)
// Other options: gemini-2.5-flash-lite (faster/cheaper), gemini-2.5-pro (smarter/slower)
// Check https://ai.google.dev/gemini-api/docs/models for latest models
const DEFAULT_MODEL = 'gemini-2.5-flash';

const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY;
const GEMINI_MODEL = import.meta.env.VITE_GEMINI_MODEL || DEFAULT_MODEL;
const GEMINI_API_URL = `https://generativelanguage.googleapis.com/v1/models/${GEMINI_MODEL}:generateContent`;

export async function getCharacterResponse(character, conversationHistory) {
  if (!GEMINI_API_KEY) {
    console.warn('VITE_GEMINI_API_KEY not found in environment variables');
    console.log('Using fallback response for testing');
    // Fallback to a simple response for testing without API
    const childLastMessage = conversationHistory[conversationHistory.length - 1]?.content || '';
    return `That's so interesting! You said "${childLastMessage}". Tell me more about that!`;
  }

  try {
    // Convert conversation history to Gemini format
    const systemPrompt = getSystemPrompt(character);

    // Build Gemini messages format - prepend system prompt as first user message
    const geminiMessages = [
      {
        role: 'user',
        parts: [{ text: systemPrompt + '\n\nNow start the conversation.' }]
      },
      {
        role: 'model',
        parts: [{ text: 'Understood! I will follow these instructions.' }]
      },
      ...conversationHistory.map(msg => ({
        role: msg.role === 'assistant' ? 'model' : 'user',
        parts: [{ text: msg.content }]
      }))
    ];

    const requestBody = {
      contents: geminiMessages,
      generationConfig: {
        temperature: 0.9,
        topK: 40,
        topP: 0.95,
        maxOutputTokens: 500, // Increased to allow complete sentences and natural responses
      }
    };

    console.log('Calling Gemini API:', GEMINI_MODEL);

    const response = await fetch(`${GEMINI_API_URL}?key=${GEMINI_API_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Gemini API error response:', errorText);
      throw new Error(`Gemini API error: ${response.status} ${response.statusText}`);
    }

    const data = await response.json();
    console.log('Gemini API response:', data);

    // Extract text from Gemini response
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!generatedText) {
      console.error('No text in Gemini response:', data);
      throw new Error('No text generated by Gemini');
    }

    return generatedText;
  } catch (error) {
    console.error('Error calling Gemini API:', error);
    // Fallback response
    return "I'm having trouble thinking right now. Can you say that again?";
  }
}
